# Generated by Django 6.0.1 on 2026-01-13 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="comment",
            options={"ordering": ["created_time"]},
        ),
        migrations.AlterModelOptions(
            name="post",
            options={"ordering": ["-created_time"]},
        ),
        migrations.RenameField(
            model_name="comment",
            old_name="created_at",
            new_name="created_time",
        ),
        migrations.RenameField(
            model_name="post",
            old_name="created_at",
            new_name="created_time",
        ),
    ]
