# Generated by Django 6.0.1 on 2026-01-13 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_alter_comment_options_alter_post_options_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Comment",
            new_name="Commentary",
        ),
    ]
